wrote some basic tests using snapshots and jest
parks-and-recursion/steam_recentNews pull request #5
Opened 2019-05-25 08:24 UTC by Doughertyg

2019-05-25 18:35 UTC, PikaJoyce requested changes
"setupFiles": [
      "./setup.js"
    ]

I think your setupFiles might be wrong. Try "<rootDir>test/setup.js" instead!

2019-05-25 20:34 UTC, Doughertyg commented
Well I head to change the tests folder to '__tests__' for jest to recognize it and then when the setup file was in there it was giving me an that it wasn't a test so I don't think non test files are supposed to be in there. So I moved it out

2019-05-25 21:05 UTC, PikaJoyce commented
So, is it working now? If not, is your setup file inside of the test folder? Do you also have a jest.config file in the root directory? I got my jest to work by getting rid of the jest.config. But I still think your issue is that you're having issues with pathing. Lemme know if this works.

2019-05-28 18:32 UTC, PikaJoyce approved these changes

2019-05-28 18:35 UTC, merged